stages:
  - build
  - deploy

variables:
  TAIS_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/tais:$CI_BUILD_REF_NAME

build tais:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -f docker/rocketchat.Dockerfile -t $TAIS_RELEASE_IMAGE .
    - docker tag $TAIS_RELEASE_IMAGE "$CI_REGISTRY_IMAGE/tais:latest"
    - docker push $TAIS_RELEASE_IMAGE
    - docker push "$CI_REGISTRY_IMAGE/tais:latest"
  only:
    - /master/
  environment: development
  tags:
    - docker

deploy_to_development:
  image: cdrx/rancher-gitlab-deploy
  stage: deploy
  services:
    - docker:dind
  script:
    - upgrade --environment Development --stack Tais --service tais --new-image $TAIS_RELEASE_IMAGE --no-finish-upgrade --debug
  only:
    - /master/
  environment: development
  tags:
    - docker

deploy_to_production:
  image: cdrx/rancher-gitlab-deploy
  stage: deploy
  services:
    - docker:dind
  script:
    - upgrade --environment Production --stack Tais --service tais --new-image $TAIS_RELEASE_IMAGE --no-finish-upgrade --debug
  only:
    - tags
  environment: production
  tags:
    - docker
