version: '2'

services:
  rocketchat:
    image: rocket.chat:0.68.3
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - MAIL_URL=smtp://smtp.email
      - ADMIN_USERNAME=admin
      - ADMIN_PASS=admin
    depends_on:
      - mongo
    ports:
      - 3000:3000

  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --oplogSize 128 --replSet rs0

  mongo-init-replica:
    image: mongo:3.2
    command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"'
    depends_on:
      - mongo

  tais:
    build:
      context: .
      dockerfile: ./docker/rocketchat.Dockerfile
    environment:
      - TRAINING_EPOCHS=300
      - TAIS_PORT=5005
      - CREDENTIALS=/tais/credentials.yml
    ports:
      - 5005:5005
    volumes:
      - ./tais:/tais
    depends_on:
      - rocketchat

  tais-console:
    build:
      context: .
      dockerfile: ./docker/console.Dockerfile
    environment:
      - TRAINING_EPOCHS=300
    volumes:
      - ./tais:/tais

  landing-page:
    image: python:3.6
    entrypoint: bash -c "cd /app && python -m http.server 8000"
    ports:
      - 8000:8000
    volumes:
      - ./landing-page:/app
