version: '2'

services:
  rocketchat:
    image: rocket.chat:0.68.3
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - ADMIN_USERNAME=admin
      - ADMIN_PASS=admin
    depends_on:
      - mongo
    ports:
      - 3000:3000

  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --oplogSize 128

  rouana:
    build:
      context: .
      dockerfile: ./docker/tais/Dockerfile
    environment:
      - TRAINING_EPOCHS=300
      - ROUANA_PORT=5005
      - CREDENTIALS=/rouana/credentials.yml
    ports:
      - 5005:5005
    volumes:
      - ./rouana:/rouana
    depends_on:
      - rocketchat

  auth:
    image: beevelop/nginx-basic-auth
    environment:
      - HTPASSWD=./.htpasswd
      - FORWARD_PORT=8000
      - PORT=80
    links:
      - landing-page:web
    ports:
      - 8080:80
  
  landing-page:
    build:
      context: .
      dockerfile: ./docker/landing_page/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./landing_page:/landing_page

